"""
Constantes utilizadas a lo largo de la practica
"""
# Calculadora sencilla
ASCII_SUMA = 43
ASCII_RESTA = 45
# Calculadora cientifica
ASCII_MODULO = 37
ASCII_MULTIPLICACION = 42
ASCII_DIVISION = 47
ASCII_POTENCIA = 94
# Login
INPUT_PATH = "Code/Input.txt"
LLAVE_CIFRADO = 5
# GUI
LOGIN_WIDTH = 250
LOGIN_HEIGTH = 200
DEFAULT_POSTION_X =350
DEFAULT_POSTION_Y =350
CALC_WIDTH = 400
CALC_HEIGTH = 250
PANTALLA_LOGIN = 1
PANTALLA_CALCULADORA = 2